### ISSUE TITLE
Colour scheme / font for log panel non-ideal

### ISSUE THREAD

**Issue by graeme-winter** [ccp4/DUI2#12]
![Screenshot 2022-09-07 at 13 00 24](https://user-images.githubusercontent.com/1241716/188873358-8fb7a504-96b4-4169-858f-6e7b4c129a87.png)

**Comment by luisodls** [comment]
adding a menu that includes the "Invert Brightness" option,

See before clicking the menu:

<img width="1138" alt="Screenshot 2022-10-05 at 19 35 51" src="https://user-images.githubusercontent.com/14178049/194137920-32e8e29f-4968-4cfd-8dc0-ce34d1d5006d.png">

vs after clicking:

<img width="1138" alt="Screenshot 2022-10-05 at 19 38 49" src="https://user-images.githubusercontent.com/14178049/194137954-634e74f7-4d33-4e41-9fc8-8a08e13ed542.png">
