### ISSUE TITLE
Position of "run" button unhelpful

### ISSUE THREAD

**Issue by graeme-winter** [ccp4/DUI2#14]
Conventionally this is below the data entry area -> going above to find it is unusual (I appreciate that this is an i2 motif as well) 

Conventionally you start from the top left and work to the bottom right of a GUI, as illustrated well by the web form that I am filling in right now.

**Comment by luisodls** [comment]
Now the user can chose between one of the following layouts:


![Screenshot_layout_01](https://github.com/ccp4/DUI2/assets/14178049/dcc8133c-c66b-441a-9b58-1f042af1740a)

or

![Screenshot_layout_02](https://github.com/ccp4/DUI2/assets/14178049/f6b4dffa-5840-4450-ab56-180649db2fde)

or

![Screenshot_layout_03](https://github.com/ccp4/DUI2/assets/14178049/bc09a3e8-031b-4e76-8ae0-b8131ca6d4b9)

**Comment by luisodls** [comment]
The first one will be the default one, as it has the best of both worlds: 
1- Imosflm-like traditional style 
2- More economical use of space and preparing for future Web-App implementation
