### ISSUE TITLE
Default DUI2 GUI size is not wide enough for the text shown in the log panel

### ISSUE THREAD

**Issue by graeme-winter** [ccp4/DUI2#17]
![Screenshot 2022-09-07 at 13 12 06](https://user-images.githubusercontent.com/1241716/188875317-e71c38c9-1bb9-4363-a699-8d5616d46033.png)

as an illustration. I have not resized the window.

**Comment by luisodls** [comment]
Default size is now significantly bigger

**Comment by luisodls** [comment]
![Screenshot_DUI2_import](https://user-images.githubusercontent.com/14178049/196261865-6c4f07cd-2ee3-480e-bd07-eba0d4f2a270.png)

**Comment by luisodls** [comment]
you can imagine the size of the window by looking at the size of the fonts in the log
