### ISSUE TITLE
Under "advanced" options please can we have a search

### ISSUE THREAD

**Issue by graeme-winter** [ccp4/DUI2#21]
Looking through the advanced options for e.g. `dials.index` (to find where the joint index option is) I find myself wishing I could search for e.g. "joint"

**Comment by graeme-winter** [comment]
Scrolling I eventually found it but it could have been much easier to find.

**Comment by dagewa** [comment]
This is something that _does_ work on DUI1, so maybe that can be re-used here

**Comment by luisodls** [comment]
Dui2 actually _**does**_ have a search feature, I made the result bigger and colorful so is more visible
