### ISSUE TITLE
Add ability to run dials.cosym

### ISSUE THREAD

**Issue by graeme-winter** [ccp4/DUI2#24]
If I import e.g. 10 data sets in place of `dials.symmetry` it would be good to be able to run `dials.cosym` -> can merge multiple sweeps (I do not see how to do this otherwise)

**Comment by graeme-winter** [comment]
![Screenshot 2022-09-08 at 11 20 34](https://user-images.githubusercontent.com/1241716/189098489-79dfa5f0-1fba-4808-ac60-22f507c2d3af.png)


TIL: there are hidden features

**Comment by luisodls** [comment]
And you call that a hidden feature? Wait until you find the Easter egg ;)

**Comment by luisodls** [comment]
Now it is running properly, with it's own page
