### ISSUE TITLE
In scaling, I cannot type in resolution limit

### ISSUE THREAD

**Issue by graeme-winter** [ccp4/DUI2#25]
![Screenshot 2022-09-08 at 11 45 31](https://user-images.githubusercontent.com/1241716/189103208-62dfa46d-3a70-419a-9847-ccd82c4ac8bb.png)

I have a text prompt - however
 - I cannot delete _None_
 - I cannot type digits

This seems pretty fundamentally broken for a text box to input numbers

**Comment by graeme-winter** [comment]
If I click the "up" arrow _1.00_ appears and then I can delete the value and type in numbers 🤔

**Comment by luisodls** [comment]
This also happens in integrate step, looks like any parameter in the _simple_ tab that I do not have a default value I put a `None` default which is problematic, as soon as I find default values I will fix it.

**Comment by luisodls** [comment]
Solved for index, Integrate, scale and symmetry, they all had the same issue
