### ISSUE TITLE
Capitalisation of labels etc.

### ISSUE THREAD

**Issue by dagewa** [ccp4/DUI2#30]
There are a number of inconsistencies in capitalisation of labels in the interface. For example,

- ![image](https://user-images.githubusercontent.com/11502083/200272674-d70d9701-f848-44cb-aef9-9fc9fc5f96e4.png)
- ![image](https://user-images.githubusercontent.com/11502083/200272697-f2cf0ad1-e0a2-462b-a02a-73f771cff1c9.png)
- ![image](https://user-images.githubusercontent.com/11502083/200272745-831c1ac7-a25b-4523-92dc-7474340d72b7.png)
- ![image](https://user-images.githubusercontent.com/11502083/200272836-7ac629b0-ed3c-4b43-9060-87228e65b634.png)

(with that last one, it might be that Predict and Report are treated as proper nouns in sentence case, which would be okay except that elsewhere title case is used:
![image](https://user-images.githubusercontent.com/11502083/200273448-0b1f2303-3e30-4e5c-a1da-60603210579a.png)
)

While minor, it would be great to tidy this up before the workshop because it would improve the appearance of professionalism.

**Comment by luisodls** [comment]
![Screenshot_20221109_125925_Dui2_capitalisation](https://user-images.githubusercontent.com/14178049/200841848-ecde2772-ae77-4773-97a7-3b588a98a83d.png)

now it is significantly more consistent
