### ISSUE TITLE
Integration simple parameters

### ISSUE THREAD

**Issue by dagewa** [ccp4/DUI2#32]
![image](https://user-images.githubusercontent.com/11502083/200300282-34c4f704-e1c2-42e3-af07-eb0b9f7aa34a.png)

"High resolution limit" is the most useful parameter, so should be first in the list. Might also be worth including "Low resolution limit", which might be handy for removing low res overloads or shadowed reflections that haven't otherwise been masked.

Background algorithm default should be "Auto", as it is for the `dials.integrate` program. This then selects between `glm` and `simple` depending on whether the data are counting or integrating.

"Use profile fitting". I would suggest this is the least useful parameter, so either put it last in the list or (better?) remove it from the simple parameters tab.

**Comment by luisodls** [comment]
Solved, I also added "Low resolution limit" to scale
