### ISSUE TITLE
Zoom control icons

### ISSUE THREAD

**Issue by dagewa** [ccp4/DUI2#35]
Just logging this before I forget. DUI1 has icons for these buttons:

![image](https://user-images.githubusercontent.com/11502083/201105384-fcc6bdbd-b0fd-441e-b56d-3e7864147ec1.png)

DUI2 uses text instead, which takes up much more space

![image](https://user-images.githubusercontent.com/11502083/201105442-4eca4abc-8ab1-4e1c-8ce4-16a375de4b4e.png)

the icons are probably preferable?

**Comment by luisodls** [comment]
Done
