### ISSUE TITLE
reindex automatic row selection

### ISSUE THREAD

**Issue by dagewa** [ccp4/DUI2#39]
In DUI1, a best guess solution is given after `refine_bravais_settings`. In DUI2, there seems to be no automatic choice (the second row is not automatically highlighted):

![image](https://user-images.githubusercontent.com/11502083/201116900-4415e2e7-8592-42dd-86d2-344ab28942e2.png)

**Comment by luisodls** [comment]
Now it suggests with an arrow:

![Screenshot_reindex_table](https://user-images.githubusercontent.com/14178049/211332922-18e3ef13-a2c4-48fd-8ab3-ef666b99cf12.png)

**Comment by dagewa** [comment]
I'm going to re-open, because that's not a solution for automatic selection. The user still has to manually select that row, and the extra text there is clutter and could be confusing.

A solution to this issue needs to automatically select that row, not add text to another column of the table!

**Comment by luisodls** [comment]
It is now significantly more consistent and behaves as desired, but needs some more testing and polishing, so I will leave it opened to re-visit soon.

**Comment by luisodls** [comment]
Now is stable and consistent. Also automatically "clicks" for first time as a suggestion.
