### ISSUE TITLE
Override parameters on import

### ISSUE THREAD

**Issue by dagewa** [ccp4/DUI2#40]
DUI1 allowed to set image range and beam centre, but that isn't present in DUI2. Also, this widget is not useful:

![image](https://user-images.githubusercontent.com/11502083/201123731-bb5568ab-411b-4eb4-8b24-6587f11171a0.png)

It _would_ be useful to allow detector distance to be set to a floating point number though.

**Comment by luisodls** [comment]
Done

**Comment by dagewa** [comment]
This says done, but in practice it doesn't seem possible to easily set the image range on import.
