### ISSUE TITLE
starting dui2 hangs on diamond RedHat 7

### ISSUE THREAD

**Issue by elena-pascal** [ccp4/DUI2#41]
```
$ module load dui2
$ dui2
```

time passes

Am I meant to do something else here?

If useful:
```
$ cat /etc/redhat-release
Red Hat Enterprise Linux Workstation release 7.9 (Maipo)
```

**Comment by graeme-winter** [comment]
OK, this worked for me the other day _but_ I have also experienced this myself as well

**Comment by luisodls** [comment]
fixed during preparation for DLS-CCP4 workshop, if you find it to crash again, you may reopen it
