### ISSUE TITLE
Selecting a known job as optional does not give the usual interface

### ISSUE THREAD

**Issue by dagewa** [ccp4/DUI2#42]
I forgot to do `refine_bravais_settings` after indexing, so I ran it after `refine` instead. Then I wanted to run `refine` again, but there was no `refine` button available. I could run refinement by selecting it as an optional job, but then I don't get the standard simple/advanced parameter interface.

How can I run a refine job with the usual interface in this situation?

**Comment by luisodls** [comment]
I intentionally make it "more clever" and programmed a function  that finds commands that were already run to get to the current node, so it does not let the user to repeat the command. I don't mind if we add exception(s) to this rule.

**Comment by dagewa** [comment]
Yes, I see. I think refinement does make an exception to the rule because you might want to do multiple rounds of refinement in some circumstances

**Comment by luisodls** [comment]
exception done
