### ISSUE TITLE
[bug] mismatch versions in the install script and in the tags

### ISSUE THREAD

**Issue by saga111a** [ccp4/DUI2#53]
in installation scipt 2024.10.30
 ``` bash 
 TAG_VER="2024.10.30"
TO_CURL="https://github.com/ccp4/DUI2/archive/refs/tags/v$TAG_VER.zip"
curl -L -O $TO_CURL
```

in [tags](https://github.com/ccp4/DUI2/tags) 202**3**.10.30 
![image](https://github.com/user-attachments/assets/72d7cdca-c012-44ef-a6d6-0e5d03032d0f)

**Comment by luisodls** [comment]
I just did a new tag with the correct version and removed the wrong tag, thanks for the info.

closing the ussue now
